# Generated by Django 4.2.3 on 2023-08-10 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, null=True, upload_to='August102023')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 18, 18, 58, 541469))),
            ],
        ),
    ]
