# Generated by Django 4.2.3 on 2023-08-12 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 15, 32, 42, 493987)),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to='August122023'),
        ),
    ]
