# Generated by Django 4.2.3 on 2023-08-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_files_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='systmfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='systm')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 16, 15, 11, 28, 530319))),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 15, 11, 28, 529318)),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to='August162023'),
        ),
    ]
